# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'StripeRNDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for StripeRNDemo
  pod 'Stripe', '~> 11.2.0'

  target 'StripeRNDemo-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'tipsi-stripe', :path => '../node_modules/tipsi-stripe'

  end

  target 'StripeRNDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
